jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          password: ${USER_CHOCOLATEEN_PASSWORD}
          name: Hugo
        - id: vaugie_g
          password: ${USER_VAUGIE_G_PASSWORD}
          name: Garance
        - id: i_dont_know
          password: ${USER_I_DONT_KNOW_PASSWORD}
          name: Jeremy
        - id: nasso
          password: ${USER_NASSO_PASSWORD}
          name: Nassim
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
              - "admin"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Build"
              - "Job/Configure"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Job/Read"
            assignments:
              - "nasso"
jobs:
  - file: ./job_dsl.groovy